version: '2.1'

services:
  postit-checker:
    build: .
    volumes:
      - ./keys:/checker/keys
    ports:
      - 9338:3031
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=postit-mongo
      - MONGO_PORT=27017
      - MONGO_USER=postit_mongo
      - MONGO_PASSWORD=postit_mongo
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
  postit-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: postit_mongo
      MONGO_INITDB_ROOT_PASSWORD: postit_mongo
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
