name: enochecker_test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: enowars/action-cleanup-runner@v1
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test checker style
        run: |
          cd checker
          apt update
          DEBIAN_FRONTEND=noninteractive apt-get install libmpfr-dev libmpc-dev
          pip install -r src/requirements.txt
          pip install -r dev-requirements.txt
          make lint
  build:
    runs-on: ubuntu-latest
    env:
      ENOCHECKER_TEST_CHECKER_ADDRESS: localhost
      ENOCHECKER_TEST_CHECKER_PORT: 9338
    steps:
      - uses: enowars/action-cleanup-runner@v1
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install enochecker_test
        run: |
          python -m pip install --upgrade pip
          pip install enochecker-test
      - name: Gen checker keys
        run: |
          python3 -m pip install pycryptodome==3.11.0
          cd checker
          mkdir keys
          python3 gen_keys.py 10
      - name: Start service
        run: |
          cd service
          docker-compose up -d
      - name: Start checker
        run: |
          cd checker
          docker-compose up -d
      - name: Obtain Docker host IP
        run: |
          echo "ENOCHECKER_TEST_SERVICE_ADDRESS=$(ip -4 address show dev eth0 | grep inet | awk '{ print $2 }' | sed 's|/.*$||')" >> $GITHUB_ENV
      - name: Run enochecker_test
        run: |
          enochecker_test
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
